/**:
  ros__parameters:
    timer_period: 0.01
    history_depth: 10
    thruster_count: 8

/forward_cam:
  ros__parameters:
    camera:
      i_mx_id: 19443010B17E1C1300
      i_pipeline_type: RGBD
    stereo:
      i_depth_preset: HIGH_ACCURACY
      i_depth_filter_size: 5
      i_extended_disp: true
    left:
      i_resolution: 400P
    right:
      i_resolution: 400P
/bottom_cam:
  ros__parameters:
    camera:
      i_mx_id: 1944301021531E1300
      i_pipeline_type: RGBD
    stereo:
      i_depth_preset: HIGH_ACCURACY
      i_depth_filter_size: 5
      i_extended_disp: true
    left:
      i_resolution: 400P
    right:
      i_resolution: 400P