[project]
authors = ["Scott Hickmann <scotthickmann21@gmail.com>"]
channels = ["https://fast.prefix.dev/conda-forge"]
name = "robosub"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
python = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
libgfortran = ">=14.2.0,<15"

[environments]
jazzy = { features = ["jazzy"] }

# jazzy
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"
ros-jazzy-robot-localization = "*"
ros-jazzy-nmea-msgs = "*"
ros-jazzy-vision-msgs = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-nav-msgs = "*"
