/thrusters:
  ros__parameters:
    timer_period: 0.01
    history_depth: 10
    thruster_count: 8
    # Thruster positions in body frame
    thruster_positions:
      thruster_1: [+0.272, +0.22, -0.14]
      thruster_2: [-0.272, +0.22, -0.14]
      thruster_3: [-0.272, -0.22, -0.14]
      thruster_4: [+0.272, -0.22, -0.14]
      thruster_5: [+0.272, -0.22, +0.00]
      thruster_6: [+0.272, +0.22, +0.00]
      thruster_7: [-0.272, +0.22, +0.00]
      thruster_8: [-0.272, -0.22, +0.00]
    # Thruster orientations (pointing in the direction of positive thrust; z axis can be changed accordingly)
    thruster_orientations:
      thruster_1: [0, 0, 1]
      thruster_2: [0, 0, -1]
      thruster_3: [0, 0, 1]
      thruster_4: [0, 0, -1]
      thruster_5: [-1, -1, 0]
      thruster_6: [1, -1, 0]
      thruster_7: [-1, -1, 0]
      thruster_8: [1, -1, 0]
