std_msgs/Header header

geometry_msgs/Vector3 position              # (x, y, z) m
geometry_msgs/Vector3 linear_velocity       # (vx, vy, vz) m/s
geometry_msgs/Vector3 linear_acceleration   # (ax, ay, az) m/s^2
geometry_msgs/Quaternion orientation        # (w, x, y, z) rad
geometry_msgs/Vector3 angular_velocity      # (wx, wy, wz) rad/s
geometry_msgs/Vector3 angular_acceleration  # (ax, ay, az) rad/s^2