ekf_filter_node:
  ros__parameters:
    
    publish_tf: true
    publish_acceleration: true
    world_frame: "odom"
    odom_frame: "odom"
    base_link_frame: "base_link"
    frequency: 10.0
    sensor_timeout: 0.2
    print_diagnostics: true
    
    pose0: "/position"
    pose0_config: [false, false, true,    # x_pos, y_pos, z_pos,
                  false, false, false,  # roll, pitch, yaw,
                  false, false, false,  # x_vel, y_vel, z_vel,
                  false, false, false,  # roll_vel, pitch_vel, yaw_vel,
                  false, false, false]  # x_accel, y_accel, z_accel
    pose0_differential: false
    pose0_relative: false

    pose1: "/rotation"
    pose1_config: [false, false, false,  # x_pos, y_pos, z_pos,
                  true, true, true,     # roll, pitch, yaw,
                  false, false, false,  # x_vel, y_vel, z_vel,
                  false, false, false,  # roll_vel, pitch_vel, yaw_vel,
                  false, false, false]  # x_accel, y_accel, z_accel
    pose1_differential: false
    pose1_relative: false
    pose1_queue_size: 50

    twist0: "/velocity"
    twist0_config: [false, false, false,  # x_pos, y_pos, z_pos,
                  false, false, false,    # roll, pitch, yaw,
                  true, true, true,       # x_vel, y_vel, z_vel,
                  false, false, false,    # roll_vel, pitch_vel, yaw_vel,
                  false, false, false]    # x_accel, y_accel, z_accel
    twist0_differential: false
    twist0_relative: false

    twist1: "/angular"
    twist1_config: [false, false, false,  # x_pos, y_pos, z_pos,
                  false, false, false,    # roll, pitch, yaw,
                  false, false, false,    # x_vel, y_vel, z_vel,
                  true, true, true,       # roll_vel, pitch_vel, yaw_vel,
                  false, false, false]    # x_accel, y_accel, z_accel
    twist1_differential: false
    twist1_relative: false
    twist1_queue_size: 50

# NOTE: Fusing linear acceleration wasn't done in the old global.yaml ekf
# fusing linear acceleration can be tricky, try disabling if things aren't working.
    imu0: "/accel"
    imu0_config: [false, false, false,  # x_pos, y_pos, z_pos,
                  false, false, false,  # roll, pitch, yaw,
                  false, false, false,  # x_vel, y_vel, z_vel,
                  false, false, false,  # roll_vel, pitch_vel, yaw_vel,
                  true, true, true]     # x_accel, y_accel, z_accel
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 50
    imu0_remove_gravitational_acceleration: true
